data_topics:
  python_tutorials:
    topic_dir: "data/python_tutorials"
    chroma_collection: "python"
    allowed_domains:
      - "www.w3schools.com/python"
      - "www.python.org/doc"
      - "docs.python.org/3"
      - "www.geeksforgeeks.org"
      - "www.learnpython.org"
      - "www.tutorialspoint.com/python"
      - "www.pythontutorial.net"
      - "www.w3schools.com/datascience"
      - "realpython.com"
      - "python.land"
      - "www.machinelearningnuggets.com"
      - "dash.plotly.com"
      - "plotly.com"
    start_urls:
      - "https://www.w3schools.com/python/default.asp"
      - "https://www.python.org/doc/"
      - "https://www.geeksforgeeks.org/python-programming-language-tutorial/"
      - "https://www.learnpython.org/"
      - "https://www.tutorialspoint.com/python/index.htm"
      - "https://www.pythontutorial.net/python-basics/"
      - "https://realpython.com/tutorials/data-science/"
      - "https://python.land/data-science"
      - "https://www.machinelearningnuggets.com/python-for-data-science/"
      - "https://dash.plotly.com"
      - "https://www.geeksforgeeks.org/introduction-to-dash-in-python/"
      - "https://plotly.com/examples/"
      - "https://realpython.com/python-dash/"
    non_content_phrases:
      "www.w3schools.com":
        - "INTRO TO PROGRAMMING"
        - "Python Get Started"
        - "Assign Multiple Values"
        - "Python Data Types"
        - "Access List Items"
        - "Change List Items"
        - "Add List Items"
        - "Remove List Items"
        - "Access Set Items"
        - "Add Set Items"
        - "Remove Set Items"
        - "Python While Loops"
        - "Python For Loops"
        - "Python User Input"
        - "Python String Formatting"
        - "Python File Handling"
        - "Python Read Files"
        - "Python Write/Create Files"
        - "Python Delete Files"
        - "Matplotlib Get Started"
        - "Matplotlib Pie Charts"
        - "Mean Median Mode"
        - "Normal Data Distribution"
        - "AUC - ROC Curve"
        - "MySQL Get Started"
        - "MySQL Create Database"
        - "MySQL Create Table"
        - "MySQL Order By"
        - "MySQL Drop Table"
        - "MongoDB Get Started"
        - "MongoDB Create DB"
        - "MongoDB Drop Collection"
        - "Python Built-in Functions"
        - "Python String Methods"
        - "Python List Methods"
        - "Python Dictionary Methods"
        - "Python Tuple Methods"
        - "Python Set Methods"
        - "Python File Methods"
        - "Python How To"
        - "Remove List Duplicates"
        - "Reverse a String"
        - "Add Two Numbers"
        - "Python Study Plan"
        - "Python Interview Q&A"
        - "Kickstart your career"
        - "Get certified by completing  the    course"
        - "w 3 s c h o o l s   C E R T I F I E D     .     2 0 2 5"
        - "Track your progress - it's free!"
        - "If you want to use W3Schools services as an educational institution, team or enterprise, send us an e-mail: sales@w3schools.com"
        - "If you want to report an error, or if you want to make a suggestion, send us an e-mail: help@w3schools.com"
        - "How To Tutorial"
        - "How To Examples"
        - "Front End Certificate"
        - "W3Schools is optimized for learning and training. Examples might be simplified to improve reading and learning."
        - "Tutorials, references, and examples are constantly reviewed to avoid errors, but we cannot warrant full correctness of all content. While using W3Schools, you agree to have read and accepted our  terms of use , cookie and privacy policy ."
        - "Copyright 1999-2025  by Refsnes Data. All Rights Reserved."
        - "W3Schools is Powered by W3.CSS ."
        - "Get certified by completing the PYTHON course"
        - "    FORUM ABOUT ACADEMY"
        - "Copyright 1999-2025 by Refsnes Data. All Rights Reserved. W3Schools is Powered by W3.CSS."
        - "Der Schutz Ihrer Privatsphäre liegt uns am Herzen!"
        - "Beim Besuch unserer Website können ausgewählte Unternehmen auf bestimmte Informationen auf Ihrem Gerät und auf dieser Webseite zugreifen und diese verwenden, um relevante Anzeigen oder personalisierte Inhalte zu schalten. Bitte beachten Sie, dass Anzeigen dazu beitragen, dass unser Dienst weiterhin kostenlos bleibt. Personenbezogene Daten werden basierend auf der Zustimmung gemäß Artikel 6 Absatz 1 Buchstabe a des DSGVO-Rahmens im EU-Recht verarbeitet oder wenn ein berechtigtes Interesse gemäß Artikel 6 Absatz 1 Buchstabe f desselben vorliegt."
        - "Erfahren Sie mehr darüber, warum Ihnen dies angezeigt wird"
        - "Wir, der 'Herausgeber' und eine ausgewählte Gruppe von vertrauenswürdigen Partnern (880), die als 'Anbieter' bezeichnet werden, benötigen Ihre Zustimmung zum Zweck der Datenverarbeitung. Mit diesen Zwecken können wir Informationen auf einem Gerät speichern und/oder abrufen, wie z. B. die Cookie-Verwaltung, und personenbezogene Daten verarbeiten, wie Standardinformationen, die von einem Gerät gesendet werden, und andere eindeutige Kennungen für personalisierte Anzeigen und Inhalte, Anzeigen- und Inhaltsmessungen, Erkenntnisse über Zielgruppen und Produktentwicklungen. Mit Ihrer Zustimmung können wir und unsere Partner möglicherweise genaue Standortdaten verwenden und Geräteeigenschaften zur Identifikation aktiv abfragen."
        - "Sie können der oben beschriebenen Verarbeitung zustimmen oder auf detailliertere Informationen zugreifen und Ihre Auswahl anpassen. Die erteilte Zustimmung gilt nur für diese Website. Bitte beachten Sie, dass ein Teil der Verarbeitung Ihrer personenbezogenen Daten möglicherweise auf berechtigten Interessen beruht, für die Ihre Zustimmung nicht erforderlich ist. Sie haben jedoch das Recht, dem zu widersprechen."
        - "Sie können Ihre Einstellungen jederzeit auf der Datenschutzerklärungsseite auf unserer Website ändern."
        - "Auswahlmöglichkeiten anpassenAlle akzeptieren und Website besuchen"
        - "NumPy Getting Started"
        - "NumPy Creating Arrays"
        - "NumPy Array Indexing"
        - "NumPy Array Slicing"
        - "NumPy Data Types"
        - "NumPy Copy vs View"
        - "NumPy Array Shape"
        - "NumPy Array Reshape"
        - "NumPy Array Iterating"
        - "NumPy Array Join"
        - "NumPy Array Split"
        - "NumPy Array Search"
        - "NumPy Array Sort"
        - "NumPy Array Filter"
        - "Chi Square Distribution"
        - "ufunc Create Function"
        - "ufunc Simple Arithmetic"
        - "ufunc Rounding Decimals"
        - "ufunc Finding LCM"
        - "ufunc Finding GCD"
        - "ufunc Set Operations"
        - "NumPy Study Plan"
        - "NumPy is a Python library."
        - "NumPy is used for working with arrays."
        - "NumPy is short for \"Numerical Python\"."
        - "Pandas Getting Started"
        - "Pandas Read CSV"
        - "Pandas Read JSON"
        - "Pandas Analyzing Data"
        - "Cleaning Empty Cells"
        - "Cleaning Wrong Format"
        - "Cleaning Wrong Data"
      "www.geeksforgeeks.org":
        - "Python Tutorial | Learn Python Programming Language"
        - "Python Tutorial - Python is one of the most popular programming languages today, known for its simplicity, extensive features and library support. Its clean and straightforward syntax makes it beginner-friendly, while its powerful libraries and frameworks makes it perfect for developers. Python is:"
        - "10 min read"
        - "Python Data Structures"
        - "Python OOPs Concepts"
        - "Object Oriented Programming is a fundamental concept in Python, empowering developers to build modular, maintainable, and scalable applications. By understanding the core OOP principles (classes, objects, inheritance, encapsulation, polymorphism, and abstraction), programmers can leverage the full p"
        - "11 min read"
        - "Python Exception Handling"
        - "Python Exception Handling handles errors that occur during the execution of a program. Exception handling allows to respond to the error, instead of crashing the running program. It enables you to catch and manage errors, making your code more robust and user-friendly. Example: Trying to divide a nu"
        - "7 min read"
        - "File Handling in Python"
        - "File handling refers to the process of performing operations on a file such as creating, opening, reading, writing and closing it, through a programming interface. It involves managing the data flow between the program and the file system on the storage device, ensuring that data is handled safely a"
        - "Python Database Handling"
        - "Python Packages or Libraries"
        - "Data Science with Python"
        - "Corporate & Communications Address:"
        - "A-143, 7th Floor, Sovereign Corporate Tower, Sector- 136, Noida, Uttar Pradesh (201305)"
        - "K 061, Tower K, Gulshan Vivante Apartment, Sector 137, Noida, Gautam Buddh Nagar, Uttar Pradesh, 201305"
        - "Advertise with us"
        - "GFG Corporate Solution"
        - "Placement Training Program"
        - "DSA for Beginners"
        - "Basic DSA Problems"
        - "Top 100 DSA Interview Problems"
        - "DSA Roadmap by Sandeep Jain"
        - "All Cheat Sheets"
        - "Data Science & ML"
        - "Data Science With Python"
        - "Data Science For Beginner"
        - "Python Programming Examples"
        - "Python Interview Question"
        - "Database Management System"
        - "Digital Logic Design"
        - "High Level Design"
        - "Low Level Design"
        - "System Design Bootcamp"
        - "Top DS or Algo for CP"
        - "Company-Wise Recruitment Process"
        - "@GeeksforGeeks, Sanchhaya Education Private Limited, All rights reserved"
        - "We use cookies to ensure you have the best browsing experience on our website. By using our site, you acknowledge that you have read and understood our Cookie Policy & Privacy Policy"
        - "Got It !"
        - "Geeksforgeeks.org asks for consent to use your data"
        - "How your data is used"
        - "Personalised advertising and content, advertising and content measurement, audience research and services development"
        - "Store and/or access information on a device"
        - "Your personal data will be processed and information from your device (cookies, unique identifiers, and other device data) may be stored by, accessed by and shared with 517 TCF vendor(s) and 68 ad partner(s), or used specifically by this site."
        - "How you can withdraw consent"
        - "Look for a link at the bottom of this page to manage or withdraw consent in privacy and cookie settings"




default_topic: "python"
