data_topics:
  python_tutorials:
    topic_dir: "data/python_tutorials"
    allowed_domains:
      - "https://www.w3schools.com/python"
      - "https://www.python.org/doc"
      - "https://docs.python.org/3/"
      - "https://www.geeksforgeeks.org/"
      - "https://www.learnpython.org/"
      - "https://www.tutorialspoint.com/python/"
      - "https://www.pythontutorial.net/"
      - "https://www.w3schools.com/datascience/"
    start_urls:
      - "https://www.w3schools.com/python/default.asp"
      - "https://www.python.org/doc/"
      - "https://www.geeksforgeeks.org/python-programming-language-tutorial/"
      - "https://www.learnpython.org/"
      - "https://www.tutorialspoint.com/python/index.htm"
      - "https://www.pythontutorial.net/python-basics/"
      - "https://realpython.com/tutorials/data-science/"
    non_content_phrases:
      "https://www.w3schools.com/python":
        - "INTRO TO PROGRAMMING"
        - "Python Get Started"
        - "Assign Multiple Values"
        - "Python Data Types"
        - "Access List Items"
        - "Change List Items"
        - "Add List Items"
        - "Remove List Items"
        - "Access Set Items"
        - "Add Set Items"
        - "Remove Set Items"
        - "Python While Loops"
        - "Python For Loops"
        - "Python User Input"
        - "Python String Formatting"
        - "Python File Handling"
        - "Python Read Files"
        - "Python Write/Create Files"
        - "Python Delete Files"
        - "Matplotlib Get Started"
        - "Matplotlib Pie Charts"
        - "Mean Median Mode"
        - "Normal Data Distribution"
        - "AUC - ROC Curve"
        - "MySQL Get Started"
        - "MySQL Create Database"
        - "MySQL Create Table"
        - "MySQL Order By"
        - "MySQL Drop Table"
        - "MongoDB Get Started"
        - "MongoDB Create DB"
        - "MongoDB Drop Collection"
        - "Python Built-in Functions"
        - "Python String Methods"
        - "Python List Methods"
        - "Python Dictionary Methods"
        - "Python Tuple Methods"
        - "Python Set Methods"
        - "Python File Methods"
        - "Python How To"
        - "Remove List Duplicates"
        - "Reverse a String"
        - "Add Two Numbers"
        - "Python Study Plan"
        - "Python Interview Q&A"
        - "Kickstart your career"
        - "Get certified by completing  the    course"
        - "w 3 s c h o o l s   C E R T I F I E D     .     2 0 2 5"
        - "Track your progress - it's free!"
        - "If you want to use W3Schools services as an educational institution, team or enterprise, send us an e-mail: sales@w3schools.com"
        - "If you want to report an error, or if you want to make a suggestion, send us an e-mail: help@w3schools.com"
        - "How To Tutorial"
        - "How To Examples"
        - "Front End Certificate"
        - "W3Schools is optimized for learning and training. Examples might be simplified to improve reading and learning."
        - "Tutorials, references, and examples are constantly reviewed to avoid errors, but we cannot warrant full correctness of all content. While using W3Schools, you agree to have read and accepted our  terms of use , cookie and privacy policy ."
        - "Copyright 1999-2025  by Refsnes Data. All Rights Reserved."
        - "W3Schools is Powered by W3.CSS ."
        - "Get certified by completing the PYTHON course"
        - "    FORUM ABOUT ACADEMY"
        - "Copyright 1999-2025 by Refsnes Data. All Rights Reserved. W3Schools is Powered by W3.CSS."
        - "Der Schutz Ihrer Privatsphäre liegt uns am Herzen!"
        - "Beim Besuch unserer Website können ausgewählte Unternehmen auf bestimmte Informationen auf Ihrem Gerät und auf dieser Webseite zugreifen und diese verwenden, um relevante Anzeigen oder personalisierte Inhalte zu schalten. Bitte beachten Sie, dass Anzeigen dazu beitragen, dass unser Dienst weiterhin kostenlos bleibt. Personenbezogene Daten werden basierend auf der Zustimmung gemäß Artikel 6 Absatz 1 Buchstabe a des DSGVO-Rahmens im EU-Recht verarbeitet oder wenn ein berechtigtes Interesse gemäß Artikel 6 Absatz 1 Buchstabe f desselben vorliegt."
        - "Erfahren Sie mehr darüber, warum Ihnen dies angezeigt wird"
        - "Wir, der 'Herausgeber' und eine ausgewählte Gruppe von vertrauenswürdigen Partnern (880), die als 'Anbieter' bezeichnet werden, benötigen Ihre Zustimmung zum Zweck der Datenverarbeitung. Mit diesen Zwecken können wir Informationen auf einem Gerät speichern und/oder abrufen, wie z. B. die Cookie-Verwaltung, und personenbezogene Daten verarbeiten, wie Standardinformationen, die von einem Gerät gesendet werden, und andere eindeutige Kennungen für personalisierte Anzeigen und Inhalte, Anzeigen- und Inhaltsmessungen, Erkenntnisse über Zielgruppen und Produktentwicklungen. Mit Ihrer Zustimmung können wir und unsere Partner möglicherweise genaue Standortdaten verwenden und Geräteeigenschaften zur Identifikation aktiv abfragen."
        - "Sie können der oben beschriebenen Verarbeitung zustimmen oder auf detailliertere Informationen zugreifen und Ihre Auswahl anpassen. Die erteilte Zustimmung gilt nur für diese Website. Bitte beachten Sie, dass ein Teil der Verarbeitung Ihrer personenbezogenen Daten möglicherweise auf berechtigten Interessen beruht, für die Ihre Zustimmung nicht erforderlich ist. Sie haben jedoch das Recht, dem zu widersprechen."
        - "Sie können Ihre Einstellungen jederzeit auf der Datenschutzerklärungsseite auf unserer Website ändern."
        - "Auswahlmöglichkeiten anpassenAlle akzeptieren und Website besuchen"
        - "NumPy Getting Started"
        - "NumPy Creating Arrays"
        - "NumPy Array Indexing"
        - "NumPy Array Slicing"
        - "NumPy Data Types"
        - "NumPy Copy vs View"
        - "NumPy Array Shape"
        - "NumPy Array Reshape"
        - "NumPy Array Iterating"
        - "NumPy Array Join"
        - "NumPy Array Split"
        - "NumPy Array Search"
        - "NumPy Array Sort"
        - "NumPy Array Filter"
        - "Chi Square Distribution"
        - "ufunc Create Function"
        - "ufunc Simple Arithmetic"
        - "ufunc Rounding Decimals"
        - "ufunc Finding LCM"
        - "ufunc Finding GCD"
        - "ufunc Set Operations"
        - "NumPy Study Plan"
        - "NumPy is a Python library."
        - "NumPy is used for working with arrays."
        - "NumPy is short for \"Numerical Python\"."
        - "Pandas Getting Started"
        - "Pandas Read CSV"
        - "Pandas Read JSON"
        - "Pandas Analyzing Data"
        - "Cleaning Empty Cells"
        - "Cleaning Wrong Format"
        - "Cleaning Wrong Data"




default_topic: "python_tutorials"
